import matplotlib.pyplot as plt
import numpy as n
a=n.arange(-1,1,0.1)
b=n.arange(-10,10,0.1)
c=n.arange(-10,10,0.1)
x=n.arcsin(a)
plt.subplot(2,3,1)
plt.plot(a,x)
plt.title('sine inverse')
plt.xlabel('time')
plt.ylabel('amplitude')
y=n.exp(a)
plt.subplot(2,3,2)
plt.plot(a,y)
plt.title('exponential')
plt.xlabel('time')
plt.ylabel('amplitude')
z=n.arctan(b)
plt.subplot(2,3,3)
plt.plot(b,z)
plt.title('tan inverse')
plt.xlabel('time')
plt.ylabel('amplitude')
w=n.sinc(c)
plt.subplot(2,3,4)
plt.plot(c,w)
plt.title('sinc fn')
plt.xlabel('time')
plt.ylabel('amplitude')
v=n.arccos(a)
plt.subplot(2,3,5)
plt.plot(a,v)
plt.title('cos inverse')
plt.xlabel('time')
plt.ylabel('amplitude')
plt.show()


